spring:
  datasource:
    url: jdbc:mariadb://ec2-xx
    username: ww
    password: mm
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
